---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-apps
spec:
  project: default
  destination:
    namespace: gitops
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/vladimir-babichev/infrastructure-dependency-management/
    targetRevision: HEAD
    path: k8s/core/apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
