---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
spec:
  project: default
  destination:
    namespace: core
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/vladimir-babichev/infrastructure-dependency-management/
    targetRevision: HEAD
    path: k8s/core/pihole
    plugin:
      name: argocd-vault-plugin-helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
