---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
spec:
  project: default
  destination:
    namespace: core
    server: https://kubernetes.default.svc
  source:
    chart: traefik
    repoURL: https://helm.traefik.io/traefik
    targetRevision: "10.8.0"
    helm:
      values: |
        providers:
          kubernetesCRD:
            enabled: true
          kubernetesIngress:
            enabled: true
            publishedService:
              enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
